### ISSUE TITLE
Сделать PR в библиотеку v8runner

### ISSUE THREAD

**Issue by arkuznetsov** [alex-bob-lip/ibcmdrunner#1]
Функционал работы с ibcmd был бы очень полезен в библиотеке v8runner https://github.com/oscript-library/v8runner.

**Comment by Daabramov** [comment]
UP @alex-bob-lip, если что, готовы помочь.

**Comment by alex-bob-lip** [comment]
Пока рано. Функционал Автономного Сервера пока не устоялся, сама 1С его от релиза к релизу развивает. То, что я выложил, работало на 8.3.18, но уже падает на релизах платформы больше 8.3.20. Кроме того, хотелось бы потестировать это под Linux. И сделать отдельный класс для управления ibsrv - запуск, остановка, регистрация как службы и т.д.

**Comment by alex-bob-lip** [comment]
Релиз библиотеки запушен в  oscript-libraty hub. См. #4.
