### ISSUE TITLE
Замеченные ошибки при использовании различных методов библиотеки

### ISSUE THREAD

**Issue by akademik1986** [alex-bob-lip/ibcmdrunner#12]
Спасибо за хорошую обертку над ibcmd !  Все достойно. Но в процессе использования нашел несколько замечаний.
1.  Нет обертывания в кавычки
![image](https://user-images.githubusercontent.com/19662685/218328700-e79a8e28-2fc3-4eef-a1e8-29d73a5a94de.png)
2.  Количество()
![image](https://user-images.githubusercontent.com/19662685/218328731-fd0eebb7-8e36-4b17-84c6-546842f4b0f6.png)
3. Нет запятой в параметрах 
![image](https://user-images.githubusercontent.com/19662685/218328756-07b0e88c-b804-4083-bd39-902df47ba21d.png)
4. При использовании Версия() очищаются добавленные ранее параметры
![image](https://user-images.githubusercontent.com/19662685/218328779-26163c5d-06a6-4fd1-952a-e3529196e552.png)
![image](https://user-images.githubusercontent.com/19662685/218328787-fe832f6a-e0cb-4ecd-b068-04134e8ec464.png)

**Comment by akademik1986** [comment]
4. + 
Использование Версия() очень много где используется, рекомендую проверить весь стек.

**Comment by alex-bob-lip** [comment]
Спасибо! Исправил ошибки. Опубликовал новый релиз.
