### ISSUE TITLE
Кодировка сообщений об ошибках ibcmd

### ISSUE THREAD

**Issue by dimjmur** [alex-bob-lip/ibcmdrunner#13]
В случае если ibcmd выдает сообщение об ошибке, кодировка сообщения устанавливается не корректно. Необходимо установить кодировку в процедуре ВыполнитьКоманду() 
`Команда.УстановитьКодировкуВывода(КодировкаТекста.UTF8) `
или сделать PR?

**Comment by alex-bob-lip** [comment]
Закрыто [пулл реквестом](https://github.com/alex-bob-lip/ibcmdrunner/commit/e869600975c066b266d02ff6e7be2da0dd767430)
