### ISSUE TITLE
При использовании метода частичной загрузки файлов выходит ошибка превышения длины командной строки

### ISSUE THREAD

**Issue by akademik1986** [alex-bob-lip/ibcmdrunner#14]
При использовании метода ЗагрузитьВыбранныеФайлыКонфигурации() выходит ошибка, что слишком длинная строка для команды cmd (пишу по памяти, сообщение примерное). Пытался загрузить около 50 общих модулей. В итоге падал на том, что в методе используется Команда, построенная на командной строке.
У себя обошел это циклом и передачей модулей порциями по 10 штук в метод ЗагрузитьВыбранныеФайлыКонфигурации(). Возможно целесообразнее цикл сделать внутри метода?
Пример кода

	МассивИз10 = Новый Массив;
	Для Индекс = 0 По СписокОбъектов.ВГраница() Цикл
		Если МассивИз10.Количество() = 10 Тогда
			УправлениеИБ.ЗагрузитьВыбранныеФайлыКонфигурации(ФС.ПолныйПуть(КаталогФайловКонфигурации), МассивИз10, , Ложь);
			МассивИз10 = Новый Массив;
		КонецЕсли;
		
		МассивИз10.Добавить(СписокОбъектов.Получить(Индекс));
	КонецЦикла;
	
	Если МассивИз10.Количество() > 0 Тогда
		УправлениеИБ.ЗагрузитьВыбранныеФайлыКонфигурации(ФС.ПолныйПуть(КаталогФайловКонфигурации), МассивИз10, , Ложь);
	КонецЕсли;

**Comment by yukon39** [comment]
@akademik1986 проверь у себя выбранное решение.

**Comment by yukon39** [comment]
В тестах я указывал короткие пути - все работает.

Я правильно понимаю, что если вызвать `ibcmdrunner ... Configuration.xml` то ошибки не будет, а если вызвать
```
echo Configuration.xml > list.txt
ibcmdrunner ... < list.txt
``` 
то будет ошибка?

**Comment by yukon39** [comment]
ЕМНИП, при загрузке файла конфигурации к нему надо всегда грузить основной язык. Я с таким поведением встретился еще при работе с выгрузкой в EDT: https://github.com/khorevaa/gitsync-plugins/blob/5ed03ef4ae67bf8c925e17c38c59f54689fbda05/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/edtExport.os#L310

**Comment by yukon39** [comment]
Да, я проверил сейчас на тестах - любой файл, кроме `Configuration.xml` можно загрузить в одиночку. А `Configuration.xml` грузится только в паре с языком:
```
ВыбранныеФайлы = Новый Массив;
ВыбранныеФайлы.Добавить("Configuration.xml");
ВыбранныеФайлы.Добавить("Languages/Русский.xml");
```

**Comment by akademik1986** [comment]
Ух как. Интересно. А попробуй загрузить Configuration.xml без языка, но не через файл, а просто указанием файла, загрузит же? У меня работает)

**Comment by yukon39** [comment]
хмм, шайтанама - работает...
`infobase config import files --base-dir="tests\fixtures\1.0\files" --no-check "Configuration.xml"`

**Comment by alex-bob-lip** [comment]
Это хорошо, что такая дискуссия развернулась.  Я как раз не мог понять по какому пути пойти - через доп.файл или как предлагает akademik1986. Может быть реализовать оба варианта и отразить в документации, что  Configuration.xml должен быть в паре с языком со ссылкой на это обсуждение?

**Comment by yukon39** [comment]
Лучше, конечно, все-таки учитывать особенности платформы - т.к. для списка файлов всегда нужно будет указывать в нем язык.

С другой стороны, наверно для случая указания одного файла использовать функционал передачи выбранных файлов списком несколько избыточно. Добавлю вырожденный случай списка отдельным условием.
