### ISSUE TITLE
Добавить в хаб

### ISSUE THREAD

**Issue by EvilBeaver** [alex-bob-lip/ibcmdrunner#4]
Если есть желание добавить в хаб hub.oscript.io - просьба сообщить

**Comment by alex-bob-lip** [comment]
Добрый день, Андрей!
За последний месяц я сделал много доработок, связанных с новыми возможностями платформ 1С 8.3.20-8.3.22. Сделал дополнительно 15 тестов, прогнал на платформах 8.3.18-8.3.22 d Windows и 8.3.21-8.3.22 в Linux. Собрал релиз. Наверно теперь можно размещать в хабе.
Что для этого я должен сделать?

**Comment by EvilBeaver** [comment]
Я форкнул репо в oscript-library и дал тебе на него права. Теперь, по идее, хаб oscript должен тебя признать.
Что ты должен сделать:

1. Создать у себя в профиле токен доступа ([Developer settings](https://github.com/settings/tokens))
2. Собрать у себя на машине локально релизную версию пакета, который публикуешь `opm build <каталог с packagedef>`
3. Проверить, что полученный *.ospx файл можно установить через opm `opm install -f <ibcmdrunner.ospx>` и установка проходит без ошибок, в каталоге lib/ibcmdrunner 1Скрипта после установки лежит все, что должно лежать, и все работает
4. Отправить ospx в хаб `opm push --token <твой токен> -f ibcmdrunner.ospx`

Если push не сработает, посмотреть в справку `opm push --help` и если не поможет, написать мне, сюда или в телеграм  что именно пошло не так.

**Comment by alex-bob-lip** [comment]
Получилось разместить пакет в хабе. Спасибо!

**Comment by EvilBeaver** [comment]
Спасибо!
